/**********************************************************************************
 * Instituto Superior de Engenharia de Lisboa
 * Área Departamental de Engenharia de Electrónica e Telecomunicações e de Computadores
 * Licenciatura em Engenharia Informática e de Computadores
 * Computação Gráfica
 *
 * (c) Carlos Guedes - 2013
 **********************************************************************************/

package core;

/**
 * Interface of a touch listeners
 * 
 *  This interface is implemented by classes that needs
 *  to react to touch (i.e. mouse) events (move, click and drag)
 *  generated by the raster device.
 * 
 * @author Carlos Guedes
 *
 */
public interface ITouchListener
{
	/**
	 * Called when the mouse is moved inside the raster area
	 * 
	 * @param x X-axis coordinate of the mouse, in device coordinates
	 * @param y Y-axis coordinate of the mouse, in device coordinates
	 */
	void onMove(int x, int y);

	/**
	 * Called when the mouse is clicked inside the raster area
	 * 
	 * @param x X-axis coordinate of the mouse, in device coordinates
	 * @param y Y-axis coordinate of the mouse, in device coordinates
	 * @param button that is pressed
	 */
	void onClick(int x, int y, int button);

	/**
	 * Called when a drag occurred inside the raster area.
	 * A drag occurs on a "click and move" mouse operation-
	 * 
	 * @param x X-axis coordinate of the mouse, in device coordinates
	 * @param y Y-axis coordinate of the mouse, in device coordinates
	 * @param button that is pressed
	 */
	void onDrag(int x, int y, int button);
}
